//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netminiproject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int id_of_courses { get; set; }
        public string name_of_courses { get; set; }
        public string trainers { get; set; }
        public string passedtrainers { get; set; }
    }
}
