//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netminiproject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class notation
    {
        public int Id { get; set; }
        public string Certifications { get; set; }
        public string Validation_of_ECTS_credits { get; set; }
        public string work_experience { get; set; }
        public string questionmark { get; set; }
        public string finalmark { get; set; }
        public string ifpassed { get; set; }
    }
}
