//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netminiproject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string Promotion_during_validation { get; set; }
        public string Current_Promotion { get; set; }
        public string E_mail { get; set; }
        public string Campus { get; set; }
        public string Courses_that_he_would_teach { get; set; }
        public string Courses_that_he_already_teach { get; set; }
        public string The_campus_on_which_he_has_already_given_a_course { get; set; }
        public string The_campus_on_which_he_would_give_a_course { get; set; }
    }
}
